# Generated by Django 5.2.4 on 2025-07-06 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('address', models.CharField(max_length=200, verbose_name='Adres obiektu')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('details', models.TextField(verbose_name='Opis pracy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_photos/', verbose_name='Zdjęcie')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.order')),
            ],
        ),
    ]
